run_dir = "run"

molecules = [
    "/mnt/d/EGFR_pipeline/results/haddock_runs/WT_Cetuximab/input/WT_ECD_clean_A.pdb",
    "/mnt/d/EGFR_pipeline/results/haddock_runs/WT_Cetuximab/input/Cetuximab_Fab_merged.pdb"
]

########################################
# 0) Topology
########################################
[topoaa]

########################################
# 1) Rigid-body docking (it0)
########################################
[rigidbody]
ambig_fname = "/mnt/d/EGFR_pipeline/results/haddock_runs/WT_Cetuximab/restraints/ambig_clean.tbl"
sampling = 500

########################################
# 2) Score/evaluate it0 models
########################################
[caprieval]

########################################
# 3) Select best it0 models for refinement
########################################
[seletop]
select = 200

########################################
# 4) Semi-flexible refinement (it1)
########################################
[flexref]
ambig_fname = "/mnt/d/EGFR_pipeline/results/haddock_runs/WT_Cetuximab/restraints/ambig_clean.tbl"

########################################
# 5) Score/evaluate refined models
########################################
[caprieval]

########################################
# 6) Select best refined models for clustering
########################################
[seletop]
select = 100

########################################
# 7) Cluster by FCC (standard HADDOCK clustering)
########################################
[clustfcc]

########################################
# 8) Pick top clusters and representatives
########################################
[seletopclusts]

########################################
# 9) Score/evaluate the final clusters!
########################################
[caprieval]

########################################
# 10) Interface contact map / summary
########################################
[contactmap]